add deephash configure files and dch algorithm
PaddlePaddle/PaddleClas pull request #1702
Opened 2022-02-23 11:56 UTC by Intsigstephon

1) configure file:  dch.yaml, dshsd.yaml, lcdsh.yaml
2) loss: dchloss
3) data: CustomizedCifar10
4) optimizer: SGD

2022-02-24 09:25 UTC, weisy11 requested changes

2022-02-24 09:25 UTC, weisy11 commented on ppcls/configs/DeepHash/DCH.yaml
> +# loss function config for traing/eval process
typo

2022-02-24 09:25 UTC, weisy11 commented on ppcls/data/__init__.py
> +from ppcls.data.dataloader.customized_cifar10 import CustomizedCifar10
这个dataset的名字可以再明确些，customized没有信息量

2022-02-24 09:25 UTC, weisy11 commented on ppcls/data/dataloader/customized_cifar10.py
> +        assert mode.lower() in ['train', 'test', 'train', 'test'], \
为啥有两遍

2022-02-24 09:25 UTC, weisy11 commented on ppcls/data/dataloader/customized_cifar10.py
> +            "mode should be 'train10', 'test10', 'train100' or 'test100', but got {}".format(mode)
这个注释跟上面的选项对不上

2022-02-24 09:25 UTC, weisy11 commented on ppcls/data/dataloader/customized_cifar10.py
> +        self.transform = transforms.Compose([
transform为什么不通过配置文件来配置

2022-02-24 09:25 UTC, weisy11 commented on ppcls/data/dataloader/customized_cifar10.py
> +        img = np.reshape(img, [3, 32, 32])
这里的transform为什么是直接写的

2022-02-24 09:25 UTC, weisy11 commented on ppcls/loss/deephashloss.py
> +            label, n_class).astype("float32").squeeze()
这个操作顺序跟原来不一样了，为什么要这样改，结果有无变化？

2022-02-24 09:25 UTC, weisy11 commented on ppcls/loss/deephashloss.py
> +            label, label, transpose_y=True) > 0).astype("float32") - 1
表达式太长了，拆一下

2022-02-24 09:25 UTC, weisy11 commented on ppcls/loss/deephashloss.py
> +    # [DCH] epoch:150, bit:48, dataset:nuswide_21, MAP:0.778, Best MAP: 0.794
这个注释是设么含义？为什么写在这里

2022-02-24 09:25 UTC, weisy11 commented on ppcls/loss/deephashloss.py
> +    def d(self, hi, hj):
d hi hj 是什么含义？变量名太随意了

2022-02-24 09:25 UTC, weisy11 commented on ppcls/optimizer/optimizer.py
> +class SGD(object):
为什么要加一个SGD？paddle的SGD有diff吗？

2022-02-24 09:25 UTC, weisy11 commented on ppcls/optimizer/optimizer.py
> +        return opt
从实现来看，这个类是多余的。现有的optimizer部分实现有什么问题呢？

2022-02-24 09:30 UTC, Intsigstephon commented on ppcls/configs/DeepHash/DCH.yaml
> +# loss function config for traing/eval process
这个是啥意思？

2022-02-24 09:33 UTC, Intsigstephon commented on ppcls/data/__init__.py
> +from ppcls.data.dataloader.customized_cifar10 import CustomizedCifar10
这个数据类是基于paddle已有数据集，修改了接口和transform部分，所以是定制的Cifar10；有更好的名字推荐吗？

2022-02-24 09:35 UTC, Intsigstephon commented on ppcls/data/dataloader/customized_cifar10.py
> +        assert mode.lower() in ['train', 'test', 'train', 'test'], \
这个是从源码复制过来的，确实得改下

2022-02-24 09:35 UTC, Intsigstephon commented on ppcls/data/dataloader/customized_cifar10.py
> +            "mode should be 'train10', 'test10', 'train100' or 'test100', but got {}".format(mode)
OK, 这儿得改；paddle的源码也有类似问题

2022-02-24 09:39 UTC, Intsigstephon commented on ppcls/data/dataloader/customized_cifar10.py
> +        self.transform = transforms.Compose([
区别于Common_dataset的接口；和paddle内置的数据集接口有较大差异；transform不太好配置，或者得设计另外一种配置格式

2022-02-24 09:39 UTC, Intsigstephon commented on ppcls/data/dataloader/customized_cifar10.py
> +        img = np.reshape(img, [3, 32, 32])
可以优化下

2022-02-24 09:45 UTC, weisy11 commented on ppcls/data/dataloader/customized_cifar10.py
> +        self.transform = transforms.Compose([
这里用内置的Cifar数据集有什么优势吗？

2022-02-28 08:00 UTC, Intsigstephon commented on ppcls/loss/deephashloss.py
> +            label, label, transpose_y=True) > 0).astype("float32") - 1
长不是问题

2022-02-28 08:00 UTC, Intsigstephon commented on ppcls/loss/deephashloss.py
> +    # [DCH] epoch:150, bit:48, dataset:nuswide_21, MAP:0.778, Best MAP: 0.794
OK. 这块注释可以再优化下

2022-02-28 08:00 UTC, Intsigstephon commented on ppcls/loss/deephashloss.py
> +    def d(self, hi, hj):
OK

2022-02-28 08:00 UTC, Intsigstephon commented on ppcls/loss/deephashloss.py
> +            label, n_class).astype("float32").squeeze()
flatte操作和squeeze()是等价的，对结果不会有什么变化

2022-02-28 08:00 UTC, Intsigstephon commented on ppcls/optimizer/optimizer.py
> +        return opt
不多余。对paramters部分做了修改，和原来的不一样

2022-03-07 02:32 UTC, weisy11 approved these changes
LGTM

2022-03-07 02:32 UTC, merged