adapt roll op for swin transformer
PaddlePaddle/PaddleClas pull request #2533
Opened 2022-12-05 10:27 UTC by kuizhiqing

use cached roll op for swin transformer.

2022-12-06 09:17 UTC, sneaxiy approved these changes, later dismissed
Excellent.

2022-12-06 09:44 UTC, qili93 submitted a review, later dismissed
LGTM

2022-12-06 11:09 UTC, weisy11 requested changes

2022-12-06 11:09 UTC, weisy11 commented on ppcls/arch/backbone/legendary_models/swin_transformer.py
> +        self.index_dict = {}
self.roll_with_index_select = RollWithIndexSelect.apply

2022-12-06 11:09 UTC, weisy11 commented on ppcls/arch/backbone/legendary_models/swin_transformer.py
> +roll = None
将roll移到函数内部，如果需要资源复用，可以使用singleton

2022-12-06 11:09 UTC, weisy11 commented on ppcls/arch/backbone/legendary_models/swin_transformer.py
> +roll_with_index_select = RollWithIndexSelect.apply
移到函数内或类内

2022-12-07 06:14 UTC, weisy11 approved these changes
LGTM

2022-12-07 06:14 UTC, merged