【Hackathon 5th No.69】 分类大模型--人体视觉任务SOLIDER
PaddlePaddle/PaddleClas pull request #2995
Opened 2023-10-08 07:03 UTC by Yang-Changhui

2023-10-09 08:18 UTC, cuicheng01 commented
此处为什么需要修改呢？

2023-10-09 08:18 UTC, cuicheng01 commented
> 原始代码只修改了 SwinTransformerBlock，<=修改为<;尝试在swin_transformer-variant中修改，发现修改后不起作用，因此该部分在原始代码中修改 ![image](https://user-images.githubusercontent.com/71805205/273431356-a876c545-239a-413b-bf10-8232ef38ae4c.png)

此处为什么需要修改呢

2023-10-09 08:25 UTC, Yang-Changhui commented
> > 原始代码只修改了 SwinTransformerBlock，<=修改为<;尝试在swin_transformer-variant中修改，发现修改后不起作用，因此该部分在原始代码中修改 ![image](https://user-images.githubusercontent.com/71805205/273431356-a876c545-239a-413b-bf10-8232ef38ae4c.png)
> 
> 此处为什么需要修改呢

不修改的话，在最后一个调用SwinTransformerBlock时，min(self.input_resolution)=self.window_size，导致attn_mask = None；但在solider中，最后一次attn_mask 不为None；修改后，保持一致

2023-10-11 08:21 UTC, Yang-Changhui commented
@cuicheng01 你好，请问还需要做出那些修改吗

2023-10-11 09:25 UTC, cuicheng01 commented
> @cuicheng01 你好，请问还需要做出那些修改吗

这里还是建议在 `variant`中修改哈，避免对原始网络造成可能的错误侵入

2023-10-11 09:49 UTC, Yang-Changhui commented
> > @cuicheng01 你好，请问还需要做出那些修改吗
> 
> 这里还是建议在 `variant`中修改哈，避免对原始网络造成可能的错误侵入
如果这样的话，可能导致写的variant比较冗余，这样也没问题吗

2023-10-11 12:08 UTC, Yang-Changhui commented
@cuicheng01 你好，我能否将原代码中的这部分判断条件，修改成函数，这样方便继承，而且对原代码没有影响，如下所示：
![image](https://github.com/PaddlePaddle/PaddleClas/assets/71805205/05bbe462-3cb0-4020-b4d4-080f49166e91)

2023-10-12 08:17 UTC, Yang-Changhui commented
@cuicheng01 你好，你有时间review一下吗，是否还有什么需要修改

2023-10-12 09:28 UTC, shiyutang commented
你好，是否能提供验证对齐的记录？ 包括三个模型的前向对齐结果。

2023-10-12 09:33 UTC, Yang-Changhui commented
[solider_base_forward_diff.log](https://github.com/PaddlePaddle/PaddleClas/files/12879753/solider_base_forward_diff.log)
[solider_small_forward_diff.log](https://github.com/PaddlePaddle/PaddleClas/files/12879755/solider_small_forward_diff.log)
[solider_tiny_forward_diff.log](https://github.com/PaddlePaddle/PaddleClas/files/12879759/solider_tiny_forward_diff.log)

2023-10-12 09:59 UTC, shiyutang requested changes

2023-10-12 09:59 UTC, shiyutang commented on docs/zh_CN/models/LUPerson/solider.md
> +| Pose Estimation (AP/AR)                           | COCO        | 74.4/79.6                                                    | 76.3/81.3                                                    | 76.6/
这些是用复现的模型验证的么，如果不是，建议删除，补上对齐的log

2023-10-12 09:59 UTC, shiyutang commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        # assert [H, W] == self.img_size[:2], "Input image size ({H}*{W}) doesn't match model ({}*{}).".format(H, W, self.img_size[0], self.img_size[1])
不必要注释可以删除

2023-10-12 10:11 UTC, shiyutang reviewed
swin transdformer - small 无法下载 <img width="290" alt="image" src="https://github.com/PaddlePaddle/PaddleClas/assets/34859558/76b48a54-7bb8-4b76-939b-0b5b0d1ff964">

2023-10-12 11:38 UTC, Yang-Changhui commented
@shiyutang 你好，已更新

2023-10-13 02:30 UTC, shiyutang commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +from ppcls.arch.backbone.legendary_models.swin_transformer import SwinTransformer, _load_pretrained, \
这部分导出会报错，辛苦参照这个修改为相对路径导出：https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/arch/backbone/variant_models/pp_lcnet_variant.py#L4

2023-10-13 02:32 UTC, shiyutang commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +from ppcls.arch.backbone.legendary_models.swin_transformer import SwinTransformer, _load_pretrained, \
修改后需要如下指令验证
```
cd PaddleClas
cd deploy
python python/predict_cls.py -c configs/inference_cls.yaml
```

2023-10-13 03:45 UTC, shiyutang commented on docs/zh_CN/models/LUPerson/solider.md
> +| swin_tiny_patch4_window7_224  | 链接：https://pan.baidu.com/s/1QdUviOSW2RdS3UGGxxHEAA?pwd=qcdd <br/>提取码：qcdd | 链接：https://pan.baidu.com/s/1W5zUFboMMhXETy4HEWbM3Q?pwd=45nx <br/>提取码：45nx |
辛苦替换模型链接为：https://paddleclas.bj.bcebos.com/models/SOILDER/SwinTransformer_base_patch4_window7_224_pretrained.pdparams

https://paddleclas.bj.bcebos.com/models/SOILDER/SwinTransformer_small_patch4_window7_224_pretrained.pdparams

https://paddleclas.bj.bcebos.com/models/SOILDER/SwinTransformer_tiny_patch4_window7_224_pretrained.pdparams

2023-10-13 07:39 UTC, Yang-Changhui commented
@shiyutang 你好，已经都修改好了，并且也验证过了

2023-10-13 08:11 UTC, shiyutang approved these changes, later dismissed
LGTM

2023-10-13 08:12 UTC, cuicheng01 commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        assert 0 <= self.shift_size < self.window_size, "shift_size must in 0-window_size"
类之间空两行

2023-10-13 08:12 UTC, cuicheng01 commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        **kwargs):
use_ssld，use_imagenet22k_pretrained，use_imagenet22kto1k_pretrained等参数无需暴露

2023-10-13 08:31 UTC, Yang-Changhui commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        **kwargs):
你好，这三个参数暴露是参考swin_transformer中的参数设定，因为_load_pretrained需要传入这三个参数，那请问是需要直接继承swin_transformer中的swin_tiny_patch4_window7_224这些类吗

2023-10-13 11:35 UTC, cuicheng01 commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        **kwargs):
`_load_pretrained`可以通过`**kwargs`控制，然后这三个参数可以不暴露

2023-10-13 11:43 UTC, Yang-Changhui commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        **kwargs):
是可以这样，那么我需要将这三个参数的初始化写入yml配置文件中吗，现在的配置文件并没有这三个参数

2023-10-13 12:17 UTC, Yang-Changhui commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        **kwargs):
请问需要我把swin_transformer原代码也改成这种形式吗，而且pretrained=False也可以不暴露，由**kwargs控制

2023-10-14 15:04 UTC, cuicheng01 commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +        **kwargs):
源代码无需改变哈，只改变种的代码就可以

2023-10-15 08:21 UTC, cuicheng01 commented
麻烦再提供一下验证的代码，包括torch和的paddle的，提供网盘链接就好，验证通过后，此PR可以合入

2023-10-15 08:54 UTC, Yang-Changhui commented
链接：https://pan.baidu.com/s/1SFxcaklLGAAki6AjZf_lSQ?pwd=sk36 
提取码：sk36

2023-10-16 08:58 UTC, cuicheng01 commented on ppcls/arch/backbone/variant_models/swin_transformer_variant.py
> +    "SwinTransformer_tiny_patch4_window7_224_SOLIDER":
注意到这个链接名字不太对，我已将`SOILDER`改为`SOLIDER`,麻烦更改一下吧～

2023-10-16 08:58 UTC, cuicheng01 commented on docs/zh_CN/models/LUPerson/solider.md
> +| ----------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
注意到这个链接名字不太对，我已将`SOILDER`改为`SOLIDER`,麻烦更改一下吧～

2023-10-16 08:58 UTC, cuicheng01 commented on ppcls/arch/backbone/__init__.py
> +from .variant_models.swin_transformer_variant import SwinTransformer_tiny_patch4_window7_224_SOLIDER
这个一次全部import吧

2023-10-16 08:58 UTC, cuicheng01 commented on ppcls/arch/backbone/variant_models/__init__.py
> +from .swin_transformer_variant import SwinTransformer_base_patch4_window7_224_SOLIDER
这个一次全部import吧

2023-10-18 03:02 UTC, Yang-Changhui commented
@cuicheng01 你好，已经修改完毕，麻烦有时间review下

2023-10-18 06:46 UTC, cuicheng01 approved these changes

2023-10-18 06:46 UTC, merged